### ISSUE TITLE
[autogrid] header filter support for number columns

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#1284]
When the column contains numbers, the header filter should be a combination of a select and a text field
<img width="253" alt="image" src="https://github.com/vaadin/hilla/assets/260340/ee548477-cc24-47b3-bb84-23c36ebf503f">

The select contains options for how to match the value (>, = or <), the text field value is used for matching

The above image is captured from the code
```jsx
          <Select
            renderer={() => (
              <ListBox>
                <Item value="GREATER_THAN" {...{ label: ">" }}>
                  &gt; Greater than
                </Item>
                <Item value="LESS_THAN" {...{ label: "<" }}>
                  &lt; Less than
                </Item>
                <Item value="EQUALS" {...{ label: "=" }}>
                  = Equals
                </Item>
              </ListBox>
            )}
            className={css.matchSelect}
            value="GREATER_THAN"
          ></Select>
          <TextField/>
```

and

```css
.matchSelect {
  --vaadin-field-default-width: 2em;
  margin-right: 3px;
}
.matchSelect > vaadin-select-value-button {
  --_lumo-text-field-overflow-mask-image: none !important;
}

.matchSelect::part(toggle-button) {
  display: none;
}
```

Note that the text field must support input in whatever format the grid column shows data in. If e.g. grid formats "1000" as "1,000" then filtering using both "1000" and "1,000" must work. Also the text in the field should be aligned the same way as the column data (left / right)
