### ISSUE TITLE
[autogrid] header filter support for date columns

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#1285]
When the column contains dates, the header filter should be a combination of a select and a date picker
<img width="253" alt="image" src="https://github.com/vaadin/hilla/assets/260340/88b028f1-3494-45bd-9c6b-d0e4fd97c369">

<img width="267" alt="image" src="https://github.com/vaadin/hilla/assets/260340/6e5af2ee-32a8-4fe6-92f1-1df7f51609d6">

The select contains options for how to match the value (>, = or <), the text field value is used for matching

The above image is captured from the code
```jsx
          <Select
            renderer={() => (
              <ListBox>
                <Item value="GREATER_THAN" {...{ label: ">" }}>
                  &gt; Greater than
                </Item>
                <Item value="LESS_THAN" {...{ label: "<" }}>
                  &lt; Less than
                </Item>
                <Item value="EQUALS" {...{ label: "=" }}>
                  = Equals
                </Item>
              </ListBox>
            )}
            className={css.matchSelect}
            value="GREATER_THAN"
          ></Select>
          <DatePicker></DatePicker>
```

and

```css
.matchSelect {
  --vaadin-field-default-width: 2em;
  margin-right: 3px;
}
.matchSelect > vaadin-select-value-button {
  --_lumo-text-field-overflow-mask-image: none !important;
}

.matchSelect::part(toggle-button) {
  display: none;
}
```

Note that both date, time and date + time formats should be supported the same way
