### ISSUE TITLE
Hilla-Push not working when upgrading from 1.3.19 to 1.3.23

### ISSUE THREAD

**Issue by cproinger** [vaadin/hilla#1354]
### Description of the bug 
i recently upgraded from hilla 1.3.19 to 1.3.23 and this broke hilla-push. for me it seems that with https://github.com/vaadin/hilla/commit/34e9a00b2dd0bcb08316e00a74a34e84ca8fc00f this broke. 

it tries to make a ws-connection with the path hilla/HILLA/push but atmosphere listens on /HILLA/push

we use the following spring-yml-config
```
vaadin:
  whitelisted-packages: ... # snip
  url-mapping: /hilla/app/*
  endpoint:
    prefix: 'hilla/connect'
```

### Versions:
    - Vaadin / Hilla version: hilla 1.3.23
